# coding: utf-8
"""Waylay Resources query parameters.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations  # for Python 3.7–3.9

from pydantic import (
    ConfigDict,
    Field,
)
from typing_extensions import (
    Annotated,  # >=3.11
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.get_stream_event_format_parameter import GetStreamEventFormatParameter


def _get_stream_query_alias_for(field_name: str) -> str:
    if field_name == "event_format":
        return "eventFormat"
    return field_name


class GetStreamQuery(WaylayBaseModel):
    """Model for `get_stream` query parameters."""

    event_format: Annotated[
        GetStreamEventFormatParameter | None,
        Field(
            description="The format of events in the stream.   If specified this must be `application/cloudevents+json` (make sure to correctly URL encode the `+` as `%2B`)"
        ),
    ] = None

    model_config = ConfigDict(
        protected_namespaces=(),
        extra="allow",
        alias_generator=_get_stream_query_alias_for,
        populate_by_name=True,
    )
