# coding: utf-8
"""Waylay Resources: REST Models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

version: 8.1.0

This service manages  [Waylay Resources](/#/features/resources/?id=resource) and related entities.  A _Waylay Resource_ models a real-world device or abstract entity of your IoT solution, and provides a context when processing data in the Rule Engine.  You'll interact with the _Waylay Resources_ API to create this _Digital Twin_ model,  a process that's also called _resource provisioning_.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

# import models into model package
from .array_must_contain_inner import ArrayMustContainInner
from .array_value_constraint import ArrayValueConstraint
from .attribute_item import AttributeItem
from .batch_operation_enqueued import BatchOperationEnqueued
from .batch_operation_result import BatchOperationResult
from .batch_operation_status_response import BatchOperationStatusResponse
from .batch_resource_operation import BatchResourceOperation
from .batch_resource_operation_query import BatchResourceOperationQuery
from .batch_resource_operation_query_ids_inner import (
    BatchResourceOperationQueryIdsInner,
)
from .batch_running_resource_operation import BatchRunningResourceOperation
from .batch_running_resource_operation_operation import (
    BatchRunningResourceOperationOperation,
)
from .boolean_value_constraint import BooleanValueConstraint
from .changed_event import ChangedEvent
from .cloud_metadata_event import CloudMetadataEvent
from .cloud_metadata_event_data import CloudMetadataEventData
from .constraint import Constraint
from .constraint_error import ConstraintError
from .constraint_status import ConstraintStatus
from .create_delete_event import CreateDeleteEvent
from .discovered_event import DiscoveredEvent
from .error_response import ErrorResponse
from .failure_operation_result_value import FailureOperationResultValue
from .generic_metadata_event import GenericMetadataEvent
from .halid_link import HALIdLink
from .hal_link import HALLink
from .hal_page_links import HALPageLinks
from .hal_resource_entity import HALResourceEntity
from .hal_resource_entity_all_of_embedded import HALResourceEntityAllOfEmbedded
from .hal_resource_entity_all_of_links import HALResourceEntityAllOfLinks
from .hal_resource_entity_all_of_links_children import (
    HALResourceEntityAllOfLinksChildren,
)
from .hal_resource_entity_all_of_links_parent import HALResourceEntityAllOfLinksParent
from .hal_resource_entity_all_of_links_resource_type import (
    HALResourceEntityAllOfLinksResourceType,
)
from .hal_resource_listing import HALResourceListing
from .hal_resource_listing_all_of_embedded import HALResourceListingAllOfEmbedded
from .hal_resource_type_entity import HALResourceTypeEntity
from .hal_self_links import HALSelfLinks
from .hal_self_links_links import HALSelfLinksLinks
from .hal_self_links_links_self import HALSelfLinksLinksSelf
from .hal_self_links_links_value import HALSelfLinksLinksValue
from .list_constraints200_response import ListConstraints200Response
from .metadata_entity import MetadataEntity
from .metadata_entity_location import MetadataEntityLocation
from .metadata_entity_value import MetadataEntityValue
from .metadata_event import MetadataEvent
from .nd_json_response_stream import NdJsonResponseStream
from .numeric_enum_value_constraint import NumericEnumValueConstraint
from .numeric_value_constraint import NumericValueConstraint
from .object_value_constraint import ObjectValueConstraint
from .operation_result_object import OperationResultObject
from .operation_result_object_results import OperationResultObjectResults
from .pagination_links import PaginationLinks
from .pagination_links_next import PaginationLinksNext
from .pagination_links_prev import PaginationLinksPrev
from .pagination_links_self import PaginationLinksSelf
from .paging_count import PagingCount
from .paging_result import PagingResult
from .patch_resource_entity import PatchResourceEntity
from .patch_resource_type_entity import PatchResourceTypeEntity
from .resource_change import ResourceChange
from .resource_changes_paged_response import ResourceChangesPagedResponse
from .resource_constraint_creation_response import ResourceConstraintCreationResponse
from .resource_constraint_entity import ResourceConstraintEntity
from .resource_constraint_with_id_entity import ResourceConstraintWithIdEntity
from .resource_creation_response import ResourceCreationResponse
from .resource_entity import ResourceEntity
from .resource_id import ResourceId
from .resource_listing import ResourceListing
from .resource_metadata_event import ResourceMetadataEvent
from .resource_metric import ResourceMetric
from .resource_metric_metric_type import ResourceMetricMetricType
from .resource_parent import ResourceParent
from .resource_ref_value_constraint import ResourceRefValueConstraint
from .resource_reference import ResourceReference
from .resource_sensor import ResourceSensor
from .resource_sensor_sensor import ResourceSensorSensor
from .resource_type import ResourceType
from .resource_type_change import ResourceTypeChange
from .resource_type_creation_response import ResourceTypeCreationResponse
from .resource_type_entity import ResourceTypeEntity
from .resource_type_id import ResourceTypeId
from .resource_type_listing import ResourceTypeListing
from .resource_type_with_constraints import ResourceTypeWithConstraints
from .resource_type_with_id_entity import ResourceTypeWithIdEntity
from .resource_types_changes_paged_response import ResourceTypesChangesPagedResponse
from .resource_with_id_entity import ResourceWithIdEntity
from .resourcetype_metadata_event import ResourcetypeMetadataEvent
from .ss_event_stream import SSEventStream
from .schema_validation_error import SchemaValidationError
from .string_enum_value_constraint import StringEnumValueConstraint
from .string_value_constraint import StringValueConstraint
from .success_operation_result_value import SuccessOperationResultValue
from .task_configuration import TaskConfiguration
from .validation_failure import ValidationFailure
from .value_constraint import ValueConstraint
from .version_response import VersionResponse

__all__ = [
    "ArrayMustContainInner",
    "ArrayValueConstraint",
    "AttributeItem",
    "BatchOperationEnqueued",
    "BatchOperationResult",
    "BatchOperationStatusResponse",
    "BatchResourceOperation",
    "BatchResourceOperationQuery",
    "BatchResourceOperationQueryIdsInner",
    "BatchRunningResourceOperation",
    "BatchRunningResourceOperationOperation",
    "BooleanValueConstraint",
    "ChangedEvent",
    "CloudMetadataEvent",
    "CloudMetadataEventData",
    "Constraint",
    "ConstraintError",
    "ConstraintStatus",
    "CreateDeleteEvent",
    "DiscoveredEvent",
    "ErrorResponse",
    "FailureOperationResultValue",
    "GenericMetadataEvent",
    "HALIdLink",
    "HALLink",
    "HALPageLinks",
    "HALResourceEntity",
    "HALResourceEntityAllOfEmbedded",
    "HALResourceEntityAllOfLinks",
    "HALResourceEntityAllOfLinksChildren",
    "HALResourceEntityAllOfLinksParent",
    "HALResourceEntityAllOfLinksResourceType",
    "HALResourceListing",
    "HALResourceListingAllOfEmbedded",
    "HALResourceTypeEntity",
    "HALSelfLinks",
    "HALSelfLinksLinks",
    "HALSelfLinksLinksSelf",
    "HALSelfLinksLinksValue",
    "ListConstraints200Response",
    "MetadataEntity",
    "MetadataEntityLocation",
    "MetadataEntityValue",
    "MetadataEvent",
    "NdJsonResponseStream",
    "NumericEnumValueConstraint",
    "NumericValueConstraint",
    "ObjectValueConstraint",
    "OperationResultObject",
    "OperationResultObjectResults",
    "PaginationLinks",
    "PaginationLinksNext",
    "PaginationLinksPrev",
    "PaginationLinksSelf",
    "PagingCount",
    "PagingResult",
    "PatchResourceEntity",
    "PatchResourceTypeEntity",
    "ResourceChange",
    "ResourceChangesPagedResponse",
    "ResourceConstraintCreationResponse",
    "ResourceConstraintEntity",
    "ResourceConstraintWithIdEntity",
    "ResourceCreationResponse",
    "ResourceEntity",
    "ResourceId",
    "ResourceListing",
    "ResourceMetadataEvent",
    "ResourceMetric",
    "ResourceMetricMetricType",
    "ResourceParent",
    "ResourceRefValueConstraint",
    "ResourceReference",
    "ResourceSensor",
    "ResourceSensorSensor",
    "ResourceType",
    "ResourceTypeChange",
    "ResourceTypeCreationResponse",
    "ResourceTypeEntity",
    "ResourceTypeId",
    "ResourceTypeListing",
    "ResourceTypeWithConstraints",
    "ResourceTypeWithIdEntity",
    "ResourceTypesChangesPagedResponse",
    "ResourceWithIdEntity",
    "ResourcetypeMetadataEvent",
    "SSEventStream",
    "SchemaValidationError",
    "StringEnumValueConstraint",
    "StringValueConstraint",
    "SuccessOperationResultValue",
    "TaskConfiguration",
    "ValidationFailure",
    "ValueConstraint",
    "VersionResponse",
]
