# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from pydantic import ConfigDict, SerializationInfo, model_serializer, StrictStr
from pydantic_core import from_json
from typing import Callable, Union
from typing import cast
from typing_extensions import (
    Self,  # >=3.11
)

from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr, field_validator
from pydantic import Field
from typing_extensions import Annotated
from ..models.array_must_contain_inner import ArrayMustContainInner


from ..models.value_constraint import ValueConstraint


class ArrayValueConstraint(BaseModel):
    """Specifies that a value must be an array and what type of elements it contains."""

    type: StrictStr
    element_type: ValueConstraint = Field(alias="elementType")
    min_length: Annotated[int, Field(strict=True, ge=0)] | None = Field(
        default=None, alias="minLength"
    )
    max_length: Annotated[int, Field(strict=True, ge=0)] | None = Field(
        default=None, alias="maxLength"
    )
    unique_values: StrictBool | None = Field(
        default=False,
        description="If true, all values in the array must be unique.",
        alias="uniqueValues",
    )
    contains: List[ArrayMustContainInner] | None = Field(
        default=None,
        description="Only supported if the `elementType` is `boolean`, `numeric` or `string`. Specifies values the array attribute must contain.",
    )

    @field_validator("type")
    @classmethod
    def type_validate_enum(cls, value):
        """Validate the enum."""
        if value not in ("array"):
            raise ValueError("must be one of enum values ('array')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="ignore",
    )

    @model_serializer(mode="wrap")
    def serializer(
        self, handler: Callable, info: SerializationInfo
    ) -> Dict[StrictStr, Any]:
        """The default serializer of the model.

        * Excludes `None` fields that were not set at model initialization.
        """
        model_dict = handler(self, info)
        return {
            k: v
            for k, v in model_dict.items()
            if v is not None or k in self.model_fields_set
        }

    def to_dict(self) -> dict[str, Any]:
        """Convert the ArrayValueConstraint instance to dict."""
        return self.model_dump(by_alias=True, exclude_unset=True, exclude_none=True)

    def to_json(self) -> str:
        """Convert the ArrayValueConstraint instance to a JSON-encoded string."""
        return self.model_dump_json(
            by_alias=True, exclude_unset=True, exclude_none=True
        )

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        """Create a ArrayValueConstraint instance from a dict."""
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_data: str | bytes | bytearray) -> Self:
        """Create a ArrayValueConstraint instance from a JSON-encoded string."""
        return cls.model_validate_json(json_data)


# TODO: Rewrite to not use raise_errors
ArrayValueConstraint.model_rebuild(raise_errors=False)
