# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.resource_id import ResourceId
from ..models.resource_type_id import ResourceTypeId

BatchResourceOperationQueryIdsInner = Union[
    Annotated[ResourceId, ""], Annotated[ResourceTypeId, ""]
]
"""BatchResourceOperationQueryIdsInner."""
