# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import List

from pydantic import (
    ConfigDict,
    Field,
)
from typing_extensions import (
    Annotated,  # >=3.11
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.batch_resource_operation_query_ids_inner import (
    BatchResourceOperationQueryIdsInner,
)


class BatchResourceOperationQuery(WaylayBaseModel):
    """BatchResourceOperationQuery."""

    ids: Annotated[List[BatchResourceOperationQueryIdsInner], Field(min_length=1)]

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
