# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
)

from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.batch_resource_delete_operation_action import (
    BatchResourceDeleteOperationAction,
)
from ..models.batch_resource_delete_operation_action_parameters import (
    BatchResourceDeleteOperationActionParameters,
)
from ..models.batch_resource_delete_operation_entity import (
    BatchResourceDeleteOperationEntity,
)
from ..models.batch_resource_delete_operation_query import (
    BatchResourceDeleteOperationQuery,
)


class BatchResourceDeleteOperation(WaylayBaseModel):
    """BatchResourceDeleteOperation."""

    entity: BatchResourceDeleteOperationEntity
    action: BatchResourceDeleteOperationAction
    query: BatchResourceDeleteOperationQuery
    action_parameters: BatchResourceDeleteOperationActionParameters | None = Field(
        default=None, alias="actionParameters"
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
