# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from typing import (
    Union,
    Any,
    List,
    TYPE_CHECKING,
    Optional,
    Dict,
    Literal,  # >=3.8
)
from typing_extensions import (
    Annotated,  # >=3.9
)
from pydantic import StrictStr, Field, ConfigDict


from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, field_validator
from ..models.batch_operation_result import BatchOperationResult
from ..models.batch_running_resource_operation import BatchRunningResourceOperation

from ..models.batch_operation_result import BatchOperationResult
from ..models.batch_running_resource_operation import BatchRunningResourceOperation

BatchOperationStatusResponse = Union[
    Annotated[BatchOperationResult, ""], Annotated[BatchRunningResourceOperation, ""]
]
"""BatchOperationStatusResponse."""
