# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class CloudMetadataEventDataType(str, Enum):
    """CloudMetadataEventDataType."""

    IO_DOT_WAYLAY_DOT_RESOURCES_DOT_V1_DOT_RESOURCETYPE_DOT_CREATED = (
        "io.waylay.resources.v1.resourcetype.created"
    )
    IO_DOT_WAYLAY_DOT_RESOURCES_DOT_V1_DOT_RESOURCETYPE_DOT_UPDATED = (
        "io.waylay.resources.v1.resourcetype.updated"
    )
    IO_DOT_WAYLAY_DOT_RESOURCES_DOT_V1_DOT_RESOURCETYPE_DOT_DELETED = (
        "io.waylay.resources.v1.resourcetype.deleted"
    )
    IO_DOT_WAYLAY_DOT_RESOURCES_DOT_V1_DOT_RESOURCE_DOT_CREATED = (
        "io.waylay.resources.v1.resource.created"
    )
    IO_DOT_WAYLAY_DOT_RESOURCES_DOT_V1_DOT_RESOURCE_DOT_UPDATED = (
        "io.waylay.resources.v1.resource.updated"
    )
    IO_DOT_WAYLAY_DOT_RESOURCES_DOT_V1_DOT_RESOURCE_DOT_DELETED = (
        "io.waylay.resources.v1.resource.deleted"
    )
    IO_DOT_WAYLAY_DOT_RESOURCES_DOT_V1_DOT_RESOURCE_DOT_DISCOVERED = (
        "io.waylay.resources.v1.resource.discovered"
    )

    def __str__(self) -> str:
        return str(self.value)
