# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict

from pydantic import (
    ConfigDict,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.cloud_metadata_event_data_source import CloudMetadataEventDataSource
from ..models.cloud_metadata_event_data_type import CloudMetadataEventDataType
from ..models.metadata_event import MetadataEvent


class CloudMetadataEvent(WaylayBaseModel):
    """CloudMetadataEvent."""

    id: Dict[str, Any]
    source: CloudMetadataEventDataSource
    subject: Dict[str, Any]
    type: CloudMetadataEventDataType
    data: MetadataEvent | None = None
    time: datetime

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="ignore",
    )
