# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import List

from pydantic import (
    ConfigDict,
    Field,
    StrictStr,
)
from typing_extensions import (
    Annotated,  # >=3.11
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.attribute_item import AttributeItem


class Constraint(WaylayBaseModel):
    """Constraint on the attributes of a Resource."""

    name: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="Name for the _Resource Constraint_"
    )
    description: StrictStr | None = Field(
        default=None, description="A description for the _Resource Constraint_"
    )
    attributes: List[AttributeItem] = Field(
        description="List of attribute descriptions"
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
