# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.hal_resource_entity_all_of_links_children import (
    HALResourceEntityAllOfLinksChildren,
)
from ..models.hal_resource_entity_all_of_links_parent import (
    HALResourceEntityAllOfLinksParent,
)
from ..models.hal_resource_entity_all_of_links_resource_type import (
    HALResourceEntityAllOfLinksResourceType,
)


class HALResourceEntityAllOfLinks(WaylayBaseModel):
    """HALResourceEntityAllOfLinks."""

    parent: HALResourceEntityAllOfLinksParent | None = None
    children: HALResourceEntityAllOfLinksChildren | None = None
    resource_type: HALResourceEntityAllOfLinksResourceType | None = Field(
        default=None, alias="resourceType"
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
