# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.pagination_links_next import PaginationLinksNext
from ..models.pagination_links_prev import PaginationLinksPrev
from ..models.pagination_links_self import PaginationLinksSelf


class PaginationLinks(WaylayBaseModel):
    """HAL links for pagination."""

    var_self: PaginationLinksSelf = Field(alias="self")
    next: PaginationLinksNext | None = None
    prev: PaginationLinksPrev | None = None

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
