# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.resource_metric_metric_type_one_of import ResourceMetricMetricTypeOneOf
from ..models.resource_metric_metric_type_one_of1 import ResourceMetricMetricTypeOneOf1
from ..models.resource_metric_metric_type_one_of2 import ResourceMetricMetricTypeOneOf2
from ..models.resource_metric_metric_type_one_of3 import ResourceMetricMetricTypeOneOf3
from ..models.resource_metric_metric_type_one_of4 import ResourceMetricMetricTypeOneOf4

ResourceMetricMetricType = Union[
    Annotated[ResourceMetricMetricTypeOneOf, ""],
    Annotated[ResourceMetricMetricTypeOneOf1, ""],
    Annotated[ResourceMetricMetricTypeOneOf2, ""],
    Annotated[ResourceMetricMetricTypeOneOf3, ""],
    Annotated[ResourceMetricMetricTypeOneOf4, ""],
]
"""How measurements should be treated as a time series.."""
