# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class ResourceMetricMetricTypeOneOf(str, Enum):
    """A number per second (implies that unit ends on ‘/s’)."""

    RATE = "rate"

    def __str__(self) -> str:
        return str(self.value)
