"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Annotated, TypeAlias

ResourceId: TypeAlias = Annotated[str, "A _Resource_ id generated by the Waylay System"] | Annotated[str, "A _Resource_ id assigned by the user upon creation"]
"""Primary identifier of a _Resource_."""
