# coding: utf-8
"""Waylay Resources models.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict

from pydantic import (
    ConfigDict,
    Field,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.discovered_event_type import DiscoveredEventType
from ..models.resource_entity import ResourceEntity
from ..models.resource_metadata_event_all_of_object_type import (
    ResourceMetadataEventAllOfObjectType,
)


class ResourceMetadataEvent(WaylayBaseModel):
    """ResourceMetadataEvent."""

    type: DiscoveredEventType
    object_type: ResourceMetadataEventAllOfObjectType = Field(alias="objectType")
    timestamp: datetime
    resource: ResourceEntity
    old_values: Dict[str, Any] | None = Field(
        default=None,
        description="old values of all attributes that have changed",
        alias="oldValues",
    )
    message: Dict[str, Any] | None = Field(
        default=None, description="The broker message that triggered the discovery"
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
