# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.array_must_contain_inner import (
        ArrayMustContainInner,
    )

    ArrayMustContainInnerAdapter = TypeAdapter(ArrayMustContainInner)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

array_must_contain_inner_model_schema = json.loads(
    r"""{
  "title" : "Array_Must_Contain_inner",
  "oneOf" : [ {
    "type" : "boolean"
  }, {
    "type" : "number"
  }, {
    "type" : "string"
  } ]
}
""",
    object_hook=with_example_provider,
)
array_must_contain_inner_model_schema.update({"definitions": MODEL_DEFINITIONS})

array_must_contain_inner_faker = JSF(
    array_must_contain_inner_model_schema, allow_none_optionals=1
)


class ArrayMustContainInnerStub:
    """ArrayMustContainInner unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return array_must_contain_inner_faker.generate()

    @classmethod
    def create_instance(cls) -> "ArrayMustContainInner":
        """Create ArrayMustContainInner stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return ArrayMustContainInnerAdapter.validate_python(cls.create_json())
