# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.batch_resource_operation import (
        BatchResourceOperation,
    )

    BatchResourceOperationAdapter = TypeAdapter(BatchResourceOperation)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_resource_operation_model_schema = json.loads(
    r"""{
  "required" : [ "action", "entity", "query" ],
  "type" : "object",
  "properties" : {
    "entity" : {
      "$ref" : "#/components/schemas/BatchResourceOperation_entity"
    },
    "action" : {
      "$ref" : "#/components/schemas/BatchResourceOperation_action"
    },
    "query" : {
      "$ref" : "#/components/schemas/BatchResourceOperation_query"
    }
  }
}
""",
    object_hook=with_example_provider,
)
batch_resource_operation_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_resource_operation_faker = JSF(
    batch_resource_operation_model_schema, allow_none_optionals=1
)


class BatchResourceOperationStub:
    """BatchResourceOperation unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_resource_operation_faker.generate()

    @classmethod
    def create_instance(cls) -> "BatchResourceOperation":
        """Create BatchResourceOperation stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BatchResourceOperationAdapter.validate_python(cls.create_json())
