# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.batch_resource_delete_operation import (
        BatchResourceDeleteOperation,
    )

    BatchResourceDeleteOperationAdapter = TypeAdapter(BatchResourceDeleteOperation)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_resource_delete_operation_model_schema = json.loads(
    r"""{
  "title" : "BatchResourceDeleteOperation",
  "required" : [ "action", "entity", "query" ],
  "type" : "object",
  "properties" : {
    "entity" : {
      "$ref" : "#/components/schemas/BatchResourceDeleteOperation_entity"
    },
    "action" : {
      "$ref" : "#/components/schemas/BatchResourceDeleteOperation_action"
    },
    "query" : {
      "$ref" : "#/components/schemas/BatchResourceDeleteOperation_query"
    },
    "actionParameters" : {
      "$ref" : "#/components/schemas/BatchResourceDeleteOperation_actionParameters"
    }
  }
}
""",
    object_hook=with_example_provider,
)
batch_resource_delete_operation_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_resource_delete_operation_faker = JSF(
    batch_resource_delete_operation_model_schema, allow_none_optionals=1
)


class BatchResourceDeleteOperationStub:
    """BatchResourceDeleteOperation unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_resource_delete_operation_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "BatchResourceDeleteOperation":
        """Create BatchResourceDeleteOperation stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                BatchResourceDeleteOperationAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return BatchResourceDeleteOperationAdapter.validate_python(
            json, context={"skip_validation": True}
        )
