# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.deleted_resource_event import (
        DeletedResourceEvent,
    )

    DeletedResourceEventAdapter = TypeAdapter(DeletedResourceEvent)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

deleted_resource_event_model_schema = json.loads(
    r"""{
  "allOf" : [ {
    "$ref" : "#/components/schemas/DeletedEvent"
  }, {
    "properties" : {
      "cascadeDelete" : {
        "$ref" : "#/components/schemas/CascadeDeleteValues"
      }
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
deleted_resource_event_model_schema.update({"definitions": MODEL_DEFINITIONS})

deleted_resource_event_faker = JSF(
    deleted_resource_event_model_schema, allow_none_optionals=1
)


class DeletedResourceEventStub:
    """DeletedResourceEvent unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return deleted_resource_event_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "DeletedResourceEvent":
        """Create DeletedResourceEvent stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                DeletedResourceEventAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return DeletedResourceEventAdapter.validate_python(
            json, context={"skip_validation": True}
        )
