# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.discovered_event import DiscoveredEvent

    DiscoveredEventAdapter = TypeAdapter(DiscoveredEvent)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

discovered_event_model_schema = json.loads(
    r"""{
  "properties" : {
    "type" : {
      "$ref" : "#/components/schemas/DiscoveredEvent_type"
    },
    "message" : {
      "type" : "object",
      "description" : "The broker message that triggered the discovery"
    }
  }
}
""",
    object_hook=with_example_provider,
)
discovered_event_model_schema.update({"definitions": MODEL_DEFINITIONS})

discovered_event_faker = JSF(discovered_event_model_schema, allow_none_optionals=1)


class DiscoveredEventStub:
    """DiscoveredEvent unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return discovered_event_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "DiscoveredEvent":
        """Create DiscoveredEvent stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                DiscoveredEventAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return DiscoveredEventAdapter.validate_python(
            json, context={"skip_validation": True}
        )
