# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.hal_resource_type_entity import (
        HALResourceTypeEntity,
    )

    HALResourceTypeEntityAdapter = TypeAdapter(HALResourceTypeEntity)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

hal_resource_type_entity_model_schema = json.loads(
    r"""{
  "type" : "object",
  "allOf" : [ {
    "$ref" : "#/components/schemas/HALSelfLinks"
  }, {
    "$ref" : "#/components/schemas/ResourceTypeEntity"
  } ]
}
""",
    object_hook=with_example_provider,
)
hal_resource_type_entity_model_schema.update({"definitions": MODEL_DEFINITIONS})

hal_resource_type_entity_faker = JSF(
    hal_resource_type_entity_model_schema, allow_none_optionals=1
)


class HALResourceTypeEntityStub:
    """HALResourceTypeEntity unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return hal_resource_type_entity_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "HALResourceTypeEntity":
        """Create HALResourceTypeEntity stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                HALResourceTypeEntityAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return HALResourceTypeEntityAdapter.validate_python(
            json, context={"skip_validation": True}
        )
