# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.hal_self_links_links_self import (
        HALSelfLinksLinksSelf,
    )

    HALSelfLinksLinksSelfAdapter = TypeAdapter(HALSelfLinksLinksSelf)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

hal_self_links__links_self_model_schema = json.loads(
    r"""{
  "allOf" : [ {
    "$ref" : "#/components/schemas/HALLink"
  }, {
    "description" : "Link to the resource"
  } ]
}
""",
    object_hook=with_example_provider,
)
hal_self_links__links_self_model_schema.update({"definitions": MODEL_DEFINITIONS})

hal_self_links__links_self_faker = JSF(
    hal_self_links__links_self_model_schema, allow_none_optionals=1
)


class HALSelfLinksLinksSelfStub:
    """HALSelfLinksLinksSelf unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return hal_self_links__links_self_faker.generate()

    @classmethod
    def create_instance(cls) -> "HALSelfLinksLinksSelf":
        """Create HALSelfLinksLinksSelf stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return HALSelfLinksLinksSelfAdapter.validate_python(cls.create_json())
