# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.hal_self_links_links_value import (
        HALSelfLinksLinksValue,
    )

    HALSelfLinksLinksValueAdapter = TypeAdapter(HALSelfLinksLinksValue)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

hal_self_links__links_value_model_schema = json.loads(
    r"""{
  "title" : "HALSelfLinks__links_value",
  "allOf" : [ {
    "$ref" : "#/components/schemas/HALIdLink"
  }, {
    "description" : "Link to a referenced resource"
  } ]
}
""",
    object_hook=with_example_provider,
)
hal_self_links__links_value_model_schema.update({"definitions": MODEL_DEFINITIONS})

hal_self_links__links_value_faker = JSF(
    hal_self_links__links_value_model_schema, allow_none_optionals=1
)


class HALSelfLinksLinksValueStub:
    """HALSelfLinksLinksValue unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return hal_self_links__links_value_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "HALSelfLinksLinksValue":
        """Create HALSelfLinksLinksValue stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                HALSelfLinksLinksValueAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return HALSelfLinksLinksValueAdapter.validate_python(
            json, context={"skip_validation": True}
        )
