# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.hal_resource_listing_all_of_embedded import (
        HALResourceListingAllOfEmbedded,
    )

    HALResourceListingAllOfEmbeddedAdapter = TypeAdapter(
        HALResourceListingAllOfEmbedded
    )
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

hal_resource_listing_all_of__embedded_model_schema = json.loads(
    r"""{
  "title" : "HALResourceListing_allOf__embedded",
  "required" : [ "values" ],
  "type" : "object",
  "properties" : {
    "values" : {
      "title" : "values",
      "type" : "array",
      "description" : "_Resource_ entities in HAL format",
      "items" : {
        "$ref" : "#/components/schemas/HALResourceEntity"
      }
    }
  }
}
""",
    object_hook=with_example_provider,
)
hal_resource_listing_all_of__embedded_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

hal_resource_listing_all_of__embedded_faker = JSF(
    hal_resource_listing_all_of__embedded_model_schema, allow_none_optionals=1
)


class HALResourceListingAllOfEmbeddedStub:
    """HALResourceListingAllOfEmbedded unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return hal_resource_listing_all_of__embedded_faker.generate()

    @classmethod
    def create_instance(cls) -> "HALResourceListingAllOfEmbedded":
        """Create HALResourceListingAllOfEmbedded stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return HALResourceListingAllOfEmbeddedAdapter.validate_python(cls.create_json())
