# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.hal_resource_entity_all_of_links_parent import (
        HALResourceEntityAllOfLinksParent,
    )

    HALResourceEntityAllOfLinksParentAdapter = TypeAdapter(
        HALResourceEntityAllOfLinksParent
    )
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

hal_resource_entity_all_of__links_parent_model_schema = json.loads(
    r"""{
  "title" : "HALResourceEntity_allOf__links_parent",
  "allOf" : [ {
    "$ref" : "#/components/schemas/HALIdLink"
  }, {
    "description" : "Link to the parent resource",
    "example" : {
      "href" : "/resources/v1/resources/658c4fb3-d25a-4bfa-aeca-3fb0009e9a8a",
      "id" : "658c4fb3-d25a-4bfa-aeca-3fb0009e9a8a"
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
hal_resource_entity_all_of__links_parent_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

hal_resource_entity_all_of__links_parent_faker = JSF(
    hal_resource_entity_all_of__links_parent_model_schema, allow_none_optionals=1
)


class HALResourceEntityAllOfLinksParentStub:
    """HALResourceEntityAllOfLinksParent unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return hal_resource_entity_all_of__links_parent_faker.generate()

    @classmethod
    def create_instance(cls) -> "HALResourceEntityAllOfLinksParent":
        """Create HALResourceEntityAllOfLinksParent stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return HALResourceEntityAllOfLinksParentAdapter.validate_python(
            cls.create_json()
        )
