# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.hal_page_links import HALPageLinks

    HALPageLinksAdapter = TypeAdapter(HALPageLinks)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

hal_page_links_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "_links" : {
      "$ref" : "#/components/schemas/Pagination_links"
    }
  }
}
""",
    object_hook=with_example_provider,
)
hal_page_links_model_schema.update({"definitions": MODEL_DEFINITIONS})

hal_page_links_faker = JSF(hal_page_links_model_schema, allow_none_optionals=1)


class HALPageLinksStub:
    """HALPageLinks unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return hal_page_links_faker.generate()

    @classmethod
    def create_instance(cls) -> "HALPageLinks":
        """Create HALPageLinks stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return HALPageLinksAdapter.validate_python(cls.create_json())
