# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.hal_self_links_links import HALSelfLinksLinks

    HALSelfLinksLinksAdapter = TypeAdapter(HALSelfLinksLinks)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

hal_self_links__links_model_schema = json.loads(
    r"""{
  "title" : "HALSelfLinks__links",
  "required" : [ "self" ],
  "type" : "object",
  "properties" : {
    "self" : {
      "$ref" : "#/components/schemas/HALSelfLinks__links_self"
    }
  },
  "additionalProperties" : {
    "$ref" : "#/components/schemas/HALSelfLinks__links_value"
  },
  "description" : "Links to related objects"
}
""",
    object_hook=with_example_provider,
)
hal_self_links__links_model_schema.update({"definitions": MODEL_DEFINITIONS})

hal_self_links__links_faker = JSF(
    hal_self_links__links_model_schema, allow_none_optionals=1
)


class HALSelfLinksLinksStub:
    """HALSelfLinksLinks unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return hal_self_links__links_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "HALSelfLinksLinks":
        """Create HALSelfLinksLinks stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                HALSelfLinksLinksAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return HALSelfLinksLinksAdapter.validate_python(
            json, context={"skip_validation": True}
        )
