# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.metadata_entity_location import (
        MetadataEntityLocation,
    )

    MetadataEntityLocationAdapter = TypeAdapter(MetadataEntityLocation)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

metadata_entity_location_model_schema = json.loads(
    r"""{
  "title" : "MetadataEntity_location",
  "required" : [ "lat", "lon" ],
  "type" : "object",
  "properties" : {
    "lat" : {
      "$ref" : "#/components/schemas/Latitude"
    },
    "lon" : {
      "$ref" : "#/components/schemas/Longitude"
    }
  },
  "description" : "A global location, expressed as a longitude-latitude pair."
}
""",
    object_hook=with_example_provider,
)
metadata_entity_location_model_schema.update({"definitions": MODEL_DEFINITIONS})

metadata_entity_location_faker = JSF(
    metadata_entity_location_model_schema, allow_none_optionals=1
)


class MetadataEntityLocationStub:
    """MetadataEntityLocation unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return metadata_entity_location_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "MetadataEntityLocation":
        """Create MetadataEntityLocation stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                MetadataEntityLocationAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return MetadataEntityLocationAdapter.validate_python(
            json, context={"skip_validation": True}
        )
