# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.metadata_event import MetadataEvent

    MetadataEventAdapter = TypeAdapter(MetadataEvent)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

metadata_event_model_schema = json.loads(
    r"""{
  "oneOf" : [ {
    "$ref" : "#/components/schemas/ResourceMetadataEvent"
  }, {
    "$ref" : "#/components/schemas/ResourcetypeMetadataEvent"
  } ]
}
""",
    object_hook=with_example_provider,
)
metadata_event_model_schema.update({"definitions": MODEL_DEFINITIONS})

metadata_event_faker = JSF(metadata_event_model_schema, allow_none_optionals=1)


class MetadataEventStub:
    """MetadataEvent unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return metadata_event_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "MetadataEvent":
        """Create MetadataEvent stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                MetadataEventAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return MetadataEventAdapter.validate_python(
            json, context={"skip_validation": True}
        )
