# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.numeric_enum_value_constraint_type import (
        NumericEnumValueConstraintType,
    )

    NumericEnumValueConstraintTypeAdapter = TypeAdapter(NumericEnumValueConstraintType)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

numeric_enum_value_constraint_type_model_schema = json.loads(
    r"""{
  "title" : "NumericEnumValueConstraint_type",
  "type" : "string",
  "enum" : [ "enum" ]
}
""",
    object_hook=with_example_provider,
)
numeric_enum_value_constraint_type_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

numeric_enum_value_constraint_type_faker = JSF(
    numeric_enum_value_constraint_type_model_schema, allow_none_optionals=1
)


class NumericEnumValueConstraintTypeStub:
    """NumericEnumValueConstraintType unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return numeric_enum_value_constraint_type_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "NumericEnumValueConstraintType":
        """Create NumericEnumValueConstraintType stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                NumericEnumValueConstraintTypeAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return NumericEnumValueConstraintTypeAdapter.validate_python(
            json, context={"skip_validation": True}
        )
