# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.pagination_links_self import (
        PaginationLinksSelf,
    )

    PaginationLinksSelfAdapter = TypeAdapter(PaginationLinksSelf)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

pagination_links_self_model_schema = json.loads(
    r"""{
  "title" : "Pagination_links_self",
  "allOf" : [ {
    "$ref" : "#/components/schemas/HALLink"
  }, {
    "description" : "Link to this page of the results",
    "example" : {
      "href" : "/resources/v1/resources?skip=300"
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
pagination_links_self_model_schema.update({"definitions": MODEL_DEFINITIONS})

pagination_links_self_faker = JSF(
    pagination_links_self_model_schema, allow_none_optionals=1
)


class PaginationLinksSelfStub:
    """PaginationLinksSelf unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return pagination_links_self_faker.generate()

    @classmethod
    def create_instance(cls) -> "PaginationLinksSelf":
        """Create PaginationLinksSelf stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return PaginationLinksSelfAdapter.validate_python(cls.create_json())
