# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.pagination_links_prev import (
        PaginationLinksPrev,
    )

    PaginationLinksPrevAdapter = TypeAdapter(PaginationLinksPrev)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

pagination_links_prev_model_schema = json.loads(
    r"""{
  "title" : "Pagination_links_prev",
  "allOf" : [ {
    "$ref" : "#/components/schemas/HALLink"
  }, {
    "description" : "Link to the previous page of the results (if available)",
    "example" : {
      "href" : "/resources/v1/resources?skip=200"
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
pagination_links_prev_model_schema.update({"definitions": MODEL_DEFINITIONS})

pagination_links_prev_faker = JSF(
    pagination_links_prev_model_schema, allow_none_optionals=1
)


class PaginationLinksPrevStub:
    """PaginationLinksPrev unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return pagination_links_prev_faker.generate()

    @classmethod
    def create_instance(cls) -> "PaginationLinksPrev":
        """Create PaginationLinksPrev stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return PaginationLinksPrevAdapter.validate_python(cls.create_json())
