# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.resource_metric_metric_type import (
        ResourceMetricMetricType,
    )

    ResourceMetricMetricTypeAdapter = TypeAdapter(ResourceMetricMetricType)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

resource_metric_metric_type_model_schema = json.loads(
    r"""{
  "title" : "ResourceMetric_metricType",
  "type" : "string",
  "description" : "How measurements should be treated as a time series.",
  "example" : "counter",
  "oneOf" : [ {
    "$ref" : "#/components/schemas/ResourceMetric_metricType_oneOf"
  }, {
    "$ref" : "#/components/schemas/ResourceMetric_metricType_oneOf_1"
  }, {
    "$ref" : "#/components/schemas/ResourceMetric_metricType_oneOf_2"
  }, {
    "$ref" : "#/components/schemas/ResourceMetric_metricType_oneOf_3"
  }, {
    "$ref" : "#/components/schemas/ResourceMetric_metricType_oneOf_4"
  } ],
  "default" : "gauge"
}
""",
    object_hook=with_example_provider,
)
resource_metric_metric_type_model_schema.update({"definitions": MODEL_DEFINITIONS})

resource_metric_metric_type_faker = JSF(
    resource_metric_metric_type_model_schema, allow_none_optionals=1
)


class ResourceMetricMetricTypeStub:
    """ResourceMetricMetricType unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return resource_metric_metric_type_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "ResourceMetricMetricType":
        """Create ResourceMetricMetricType stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ResourceMetricMetricTypeAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ResourceMetricMetricTypeAdapter.validate_python(
            json, context={"skip_validation": True}
        )
