# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.resource_changes_paged_response import (
        ResourceChangesPagedResponse,
    )

    ResourceChangesPagedResponseAdapter = TypeAdapter(ResourceChangesPagedResponse)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

resource_changes_paged_response_model_schema = json.loads(
    r"""{
  "title" : "ResourceChangesPagedResponse",
  "type" : "object",
  "allOf" : [ {
    "properties" : {
      "values" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/ResourceChange"
        }
      }
    }
  }, {
    "$ref" : "#/components/schemas/PagingResult"
  } ]
}
""",
    object_hook=with_example_provider,
)
resource_changes_paged_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

resource_changes_paged_response_faker = JSF(
    resource_changes_paged_response_model_schema, allow_none_optionals=1
)


class ResourceChangesPagedResponseStub:
    """ResourceChangesPagedResponse unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return resource_changes_paged_response_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "ResourceChangesPagedResponse":
        """Create ResourceChangesPagedResponse stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ResourceChangesPagedResponseAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ResourceChangesPagedResponseAdapter.validate_python(
            json, context={"skip_validation": True}
        )
