# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.resource_metadata_event import (
        ResourceMetadataEvent,
    )

    ResourceMetadataEventAdapter = TypeAdapter(ResourceMetadataEvent)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

resource_metadata_event_model_schema = json.loads(
    r"""{
  "allOf" : [ {
    "$ref" : "#/components/schemas/GenericMetadataEvent"
  }, {
    "required" : [ "resource" ],
    "properties" : {
      "objectType" : {
        "$ref" : "#/components/schemas/ResourceMetadataEvent_allOf_objectType"
      },
      "resource" : {
        "$ref" : "#/components/schemas/ResourceEntity"
      }
    }
  }, {
    "oneOf" : [ {
      "$ref" : "#/components/schemas/CreateDeleteEvent"
    }, {
      "$ref" : "#/components/schemas/ChangedEvent"
    }, {
      "$ref" : "#/components/schemas/DiscoveredEvent"
    } ]
  } ]
}
""",
    object_hook=with_example_provider,
)
resource_metadata_event_model_schema.update({"definitions": MODEL_DEFINITIONS})

resource_metadata_event_faker = JSF(
    resource_metadata_event_model_schema, allow_none_optionals=1
)


class ResourceMetadataEventStub:
    """ResourceMetadataEvent unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return resource_metadata_event_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "ResourceMetadataEvent":
        """Create ResourceMetadataEvent stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ResourceMetadataEventAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ResourceMetadataEventAdapter.validate_python(
            json, context={"skip_validation": True}
        )
