# coding: utf-8
"""Waylay Resources model tests.

This code was generated from the OpenAPI documentation of 'Waylay Resources'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.resources.models.with_id_required import WithIdRequired

    WithIdRequiredAdapter = TypeAdapter(WithIdRequired)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

with_id_required_model_schema = json.loads(
    r"""{
  "required" : [ "id" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string"
    }
  },
  "example" : {
    "id" : "afcea5a1-81df-44f6-bd34-e0b602a2cf3d"
  },
  "x-comment" : "Entity with a required id"
}
""",
    object_hook=with_example_provider,
)
with_id_required_model_schema.update({"definitions": MODEL_DEFINITIONS})

with_id_required_faker = JSF(with_id_required_model_schema, allow_none_optionals=1)


class WithIdRequiredStub:
    """WithIdRequired unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return with_id_required_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "WithIdRequired":
        """Create WithIdRequired stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                WithIdRequiredAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return WithIdRequiredAdapter.validate_python(
            json, context={"skip_validation": True}
        )
